# Use the official Python image from the Docker Hub
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /bot2

# Copy the current directory contents into the container at /app
COPY . /bot2

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Run app.py when the container launches
CMD ["python", "bot2.py"]



FROM python:3.9-slim
WORKDIR /bot3
COPY . /bot3
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python", "bot3.py"]


FROM python:3.9-slim
WORKDIR /bot4
COPY . /bot4
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python", "bot4.py"]


FROM python:3.9-slim
WORKDIR /bot5
COPY . /bot5
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python", "bot5.py"]


FROM python:3.9-slim
WORKDIR /bot6
COPY . /bot6
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python", "bot6.py"]